[[global]]
  name = "News"
  weight = 1
  identifier = "news"
  url = "/news/"

[[global]]
  name = "Docs"
  weight = 5
  identifier = "docs"
  url = "/documentation/"

[[global]]
  name = "Resources"
  weight = 10
  identifier = "resources"
  url = "/resources/"

[[global]]
  name = "Community"
  weight = 20
  icon = true
  identifier = "community"
  url = "/community/"

# Anything with a weight > 100 gets an external icon
[[global]]
  name = "GitHub"
  weight = 200
  identifier = "github"
  post = "external"
  url = "https://github.com/microcks/microcks"

## Documentation Menus

[[docs]]
  name = "Using"
  weight = 5
  identifier = "using"
  url = "/using/"

[[docs]]
  name = "Installing"
  weight = 15
  identifier = "installing"
  url = "/installing/"

[[docs]]
  name = "Automating"
  weight = 20
  identifier = "automating"
  url = "/automating/"

[[docs]]
  name = "Administrating"
  weight = 21
  identifier = "administrating"
  post = "break"
  url = "/administrating/"

[[docs]]
  name = "Resources"
  weight = 25
  identifier = "resources"
  url = "/resources/"

[[docs]]
  name = "Community"
  weight = 30
  identifier = "community"
  url = "/community/"
